services:
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=fccpd
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: